# Generated by Django 4.0.6 on 2022-07-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensocialmediaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=120, verbose_name='Password'),
        ),
    ]
