# Generated by Django 4.0.6 on 2022-07-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opensocialmediaapp', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=400, verbose_name='Access Token')),
                ('refresh_token', models.CharField(max_length=400, verbose_name='Refresh Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opensocialmediaapp.user')),
            ],
        ),
    ]
